#!/bin/bash

if [ -e /etc/network/interfaces ]; then
	exit 0
fi


interfaces="$(ls /sys/class/net | grep -v lo)"

{
cat <<EOF
# network interface settings; autogenerated
# Please do NOT modify this file directly, unless you know what
# you're doing.
#
# If you want to manage parts of the network configuration manually,
# please utilize the 'source' or 'source-directory' directives to do
# so.
# PVE will preserve these directives, but will NOT read its network
# configuration from sourced files, so do not attempt to move any of
# the PVE managed interfaces into external files!

auto lo
iface lo inet loopback

auto vmbr0
iface vmbr0 inet dhcp
	bridge_ports $(echo "$interfaces" | head -n 1)
	bridge_stp off
	bridge_fd 0

EOF

for iface in $interfaces; do
	echo "iface $iface inet manual"
	echo ""
done
} | tee /etc/network/interfaces


