name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      EARTHLY_ORG: ${{ secrets.EARTHLY_ORG }}
      EARTHLY_SATELLITE: ${{ secrets.EARTHLY_SATELLITE }}
    strategy:
      fail-fast: false
      matrix:
        board:
          - {"board": "odroid-m1", "kernel_ver": "5.10.198-odroid-arm64", "kernel_url": "https://github.com/jclab-joseph/odroid-m1-kernel-builder/releases/download/v5.10.198-r5/linux-image-5.10.198-odroid-arm64_5.10.198-odroid-arm64-1_arm64.deb"}
          - {"board": "orangepi5plus", "kernel_ver": "6.1.43", "kernel_url": "https://github.com/jclab-joseph/armbian-rockchip-kernel-builder/releases/download/nightly/linux-image-6.1.43_6.1.43-1_arm64.deb"}
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: ^0.8.0
          use-cache: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Build
        run: |
          earthly --ci --allow-privileged --output +single-board --BOARD=${{ matrix.board.board }} --KERNEL_VER=${{ matrix.board.kernel_ver }} --KERNEL_URL=${{ matrix.board.kernel_url }}
          ls -al
      - uses: actions/upload-artifact@v4
        with:
          name: board‐{{ matrix.board.board }}
          path: |
            output/*
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts/
          merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R ./artifacts/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifacts/*
            artifacts/*/*
